spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/computer_club_db
    username: artemkolobanov
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

bank:
  host: 192.168.1.67
  port: 8082
  card:
    number: 4535345315706872